# Uncomment this line to define a global platform for your project
platform :osx, '10.11'

target 'JINS_MEME_DataLogger' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for JINS_MEME_DataLogger
  pod 'CorePlot'
end
